export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_UPDATE = "USER UPDATED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const PROFILE_PICTURE_UPDATED = "PROFILE_PICTURE_UPDATED";
export const FILTERED_USER_LIST_LOADED = "FILTERED_USER_LIST_LOADED";

export const LOAD_COMPETITORS = "GET_COMPETITORS";

export const ORGANIZATION_CREATED = "ORGANIZATION_CREATED";
export const ORGANIZATION_LIST_LOADED = "ORGANIZATION_LIST_LOADED";
export const ORGANIZATION_LOADED = "ORGANIZATION_LOADED";
export const GET_SELECTED_ORGANIZATION = "GET_SELECTED_ORGANIZATION";
export const ORGANIZATION_SELECTED = "ORGANIZATION_SELECTED";
export const ORGANIZATION_UPDATED = "ORGANIZATION_UPDATED";
export const ALL_ORGANIZATION_LIST_LOADED = "ALL_ORGANIZATION_LIST_LOADED";
export const SET_SELECTED_FOLLOWED_ORGANIZATION =
  "SET_SELECTED_FOLLOWED_ORGANIZATION";
export const FILTER_FOR_EVENTS_UPDATED = "FILTER_FOR_EVENTS_UPDATED";

export const TEAM_CREATED = "TEAM_CREATED";
export const TEAM_DELETED = "TEAM_DELETED";
export const TEAM_SELECTED = "TEAM_SELECTED";
export const TEAM_FOLLOWED = "TEAM_FOLLOWED";
export const TEAM_UNFOLLOWED = "TEAM_UNFOLLOWED";
export const IS_FOLLOWED = "IS_FOLLOWED";
export const NOT_FOLLOWED = "NOT_FOLLOWED";
export const SET_ORGANIZATIONS_FOLLOWED_LIST =
  "SET_ORGANIZATIONS_FOLLOWED_LIST";
export const SET_TEAMS_FOLLOWED_LIST = "SET_TEAMS_FOLLOWED_LIST";
export const TEAM_ADMIN_REQUEST_SENT = "TEAM_ADMIN_REQUEST_SENT";
export const TEAM_ADMIN_REQUESTS_LOADED = "TEAM_ADMIN_REQUESTS_LOADED";
export const TEAM_ADMIN_REQUEST_UPDATED = "TEAM_ADMIN_REQUEST_UPDATED";

export const AMENITI_ADDED = "AMENITI_ADDED";
export const AMENITI_REMOVED = "AMENITI_REMOVED";
export const EVENT_CREATED = "EVENT_CREATED";
export const EVENT_DELETED = "EVENT_DELETED";
export const EVENT_LINK_UPDATED = "EVENT_LINK_UPDATED";
export const EVENT_LIST_LOADED = "EVENT_LIST_LOADED";
export const EVENT_ATTENDING_LIST_LOADED = "EVENT_ATTENDING_LIST_LOADED";

export const SPORTS_LOADED = "SPORTS_LOADED";
